Delete deck
Vinnehboom/deck_stats_app pull request #10
Opened 2024-01-23 19:56 UTC by Vinnehboom

https://extensions.dev/extensions/adamnathanlewis/ext-firestore-soft-deletes
Soft delete package we installed on Firestore to keep all deleted records referenced (works for all Documents, not just Decks)

2024-01-23 20:07 UTC, dennishavermans commented on screens/decklists/decklist/DecklistDetails.tsx
> +  const { navigate } = useNavigation<MainTabParamList>();
When i run it locally i get the following typescript error =>
`Property 'navigate' does not exist on type 'MainTabParamList'`

2024-01-23 20:09 UTC, dennishavermans commented on screens/decklists/decklist/DecklistDetails.tsx
> +        navigate("Decks", { rerender: Math.random() });
I think you could just invalidate your query by doing the following =>

```
const queryClient = useQueryClient();

const navigateAndRefresh = () => {
  navigate("Decks");
  queryClient.invalidateQueries('decks');
};
```

2024-01-23 20:16 UTC, dennishavermans commented on screens/decklists/decklist/DecklistDetails.tsx
> +        navigate("Decks", { rerender: Math.random() });
Two options here. Either we use a context provider for managing the state of deck in the app ( imo not the best way ). Option two we use react query to invalidate the query and to force a refetch. like this =>

```
import { useMutation, useQueryClient } from 'react-query';
import firestore from '@react-native-firebase/firestore';

const deleteDeck = useMutation(
  (id) => firestore().collection('Decks').doc(id).delete(),
  {
    onSuccess: () => {
      queryClient.invalidateQueries('Decks');
    },
  }
);

// In your event handler
deleteDeck.mutate(deck.id);
```

In this example, deleteDeck is a mutation function that you can call to delete a deck. When the deletion is successful, it will automatically invalidate the 'Decks' query to cause a refetch. You can replace 'Decks' with the actual query key you're using for your decks data.

2024-02-05 11:33 UTC, dennishavermans requested changes

2024-02-05 11:33 UTC, dennishavermans commented on components/decks/DeckCreationForm.tsx
> +  const createDeckMutation = useMutation({
nit: maybe we can move this to a "_queries" folder and export it and import it in this file.

2024-02-05 11:33 UTC, dennishavermans commented on helpers/useFireBaseQuery.tsx
> +import { useQuery } from "@tanstack/react-query";
I really like this 👌

2024-02-05 11:33 UTC, dennishavermans commented on screens/HomeScreen.tsx
> +        <Tab.Screen name="Decks" initialParams={{}} component={DecklistScreen} />
this looks weird imo, why would we need this to be an empty object?

2024-02-05 14:16 UTC, Vinnehboom commented on screens/HomeScreen.tsx
> +        <Tab.Screen name="Decks" initialParams={{}} component={DecklistScreen} />
Not necessary anymore, was leftover code from before!

2024-02-05 14:16 UTC, Vinnehboom commented on screens/decklists/decklist/DecklistDetails.tsx
> +  const { navigate } = useNavigation<MainTabParamList>();
Forgot to answer here, but I don't get this error anywhere where I use this line of code

2024-02-05 16:45 UTC, dennishavermans approved these changes

2024-02-05 16:52 UTC, merged